package logic;

// DIESE ITEMS STEHEN FÜR DIE WAHRHEITSWERTE
// DER EINZIEGE ZWECK IST ES KEINE ZAHLEN SONDERN ITEM NAMEN EIN ZU GEBEN

/**
 * hier werden die items dargestellt
 */

public enum Items {

    KLEINERHEILTRANK,
    MITTLERERHEILTRANK,
    GROSSERHEILTRANK,
    EPISCHERHEILTRANK,

    KRAFTINGSTEIN,
    REPERATURKIT;




}
